version: 0.2
phases:
  install:
    commands:
    - npm i --prefer-offline --no-audit
  build:
    commands:
    - npm run build --prod
artifacts:
  base-directory: dist
  files:
  - '**/*'
cache:
  paths:
  - node_modules/**/*
